services:
  - type: web
    name: lpg-parity
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn serve:app
    envVars:
      - key: LOGIN_USERNAME
        sync: false
      - key: LOGIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
